### ISSUE TITLE
Undefined variable _SESSION

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#109]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [X] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

The diagnostic pages only partially work. For example, actions involving the 'click to select' links don't complete.

## How to reproduce issue

Go to Diagnostic Site, select end-user then click on either of the 'click to select' links.
 
## Detail of issue

This error appears in the logs

[Tue Apr 24 07:18:18.604877 2018] [:error] [pid 5626] [client 193.62.24.33:35626] PHP Notice:  Undefined variable: _SESSION in /opt/CAT/web/diag/findRealm.php on line 36, referer: https://a.b.c/diag/diag.php?admin=1

**Comment by restena-sw** [comment]
This part of the system is 
a) somewhat "under construction" still and
b) heavily dependent on the existence of a database with IdP, SP, contact data. In fact, we have that for eduroam, but since my understanding is that you do this for govroam purposes where such a database doesn't exist(?) then there's no data to query behind the "click to select" instances in diag.php.

What you can rely on, also in govroam, are the tests for logged-in administrators under the action_realmcheck.php.

Anyway, the _SESSION was a valid point regardless and is fixed by my recent commit.
