### ISSUE TITLE
Linux script uses formatted string literals only present since Python 3.6

### ISSUE THREAD

**Issue by paulmenzel** [GEANT/CAT#270]
We got a report from a user that [the script](https://github.com/GEANT/CAT/files/11771582/eduroam-linux-MfmG-general.py.txt) fails to run with Python 3.5.3.

```
$ python3 eduroam-linux-MfmG-general.py
   File "eduroam-linux-MfmG-general.py", line 754
     interface += f"phase2=\"auth={Config.eap_inner}\"\n" \
                                                        ^
 SyntaxError: invalid syntax 
```

It runs with Python 3.6.0. It looks like merge/pull request https://github.com/GEANT/CAT/pull/219 introduced *Formatted string literals*, [introduced with Python 3.6][1].

Please stay as compatible with old Python (3) versions as possible.

[1]: https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498

**Comment by paulmenzel** [comment]
https://github.com/GEANT/CAT/blob/da06dd601d509a6765e46c21ee5171b3bbc8b4da/devices/linux/Files/main.py#L751-L759

**Comment by Kangie** [comment]
Python 3.6 was released 7 years ago. It went EoL just over two years ago. Python 3.5 went EOL nearly three and a half years ago.

To quote my response in 284; 

> If you are stuck using crusty old EoL python in 2023/2024 you really need to think about how to fix that, and not make everyone's scripts slower and harder to read. Please.

**Comment by DimitriPapadopoulos** [comment]
True. Which exact OS ships Python 3.5.3?

**Comment by paulmenzel** [comment]
@Kangie, CAT is supposed to run on as many systems as possible, and speed is certainly not an issue.

**Comment by paulmenzel** [comment]
> True. Which exact OS ships Python 3.5.3?

No idea, I won’t dig that out. Some user out there, starting an old outdated system wants to use the Internet with Eduroam. No idea, why they shouldn’t.

**Comment by Kangie** [comment]
> > True. Which exact OS ships Python 3.5.3?
> 
> No idea, I won’t dig that out. Some user out there, starting an old outdated system wants to use the Internet with Eduroam. No idea, why they shouldn’t.

There are plenty of reasons that an old outdated system should not connect to the internet via eduroam. :wink: 

There's really [not that much out there](https://github.com/GEANT/CAT/pull/284#issuecomment-1919093656)

EPEL will handle it for RHEL >= 7, RHEL 6 is < 4 months away from ELS (and who is actually running it on a laptop?). Even SLES 12 can install a `python36` package. to get access to a reasonably modern python. Ubuntu is the outlier as the PPAs that used to enable installation of sane python versions on 14, 16, and 18 releases have been pulled... presumably because there's an upgrade path to supported releases.

I guess it comes down to how much we should support an OS that would restrict us to using _python 2.6_ features. I think it can be safely written off, especially as our CI/CD only tests on Ubuntu 22.04 (though that should really be extended to include some other distros / releases)

**Comment by paulmenzel** [comment]
> > > True. Which exact OS ships Python 3.5.3?
> > 
> > No idea, I won’t dig that out. Some user out there, starting an old outdated system wants to use the Internet with Eduroam. No idea, why they shouldn’t.
> 
> There are plenty of reasons that an old outdated system should not connect to the internet via eduroam. 😉

Please enlighten me, which ones? Using Eduroam gives you nothing but Internet access in our environment. And not forget, how shall a user update without Internet access.

> There's really [not that much out there](https://github.com/GEANT/CAT/pull/284#issuecomment-1919093656)
> 
> EPEL will handle it for RHEL >= 7, RHEL 6 is < 4 months away from ELS (and who is actually running it on a laptop?). Even SLES 12 can install a `python36` package to get access to a reasonably modern python.

How do you install that without Internet access?

> Ubuntu is the outlier as the PPAs that used to enable installation of sane python versions on 14, 16, and 18 releases have been pulled... presumably because there's an upgrade path to supported releases.
> 
> I guess it comes down to how much we should support an OS that would restrict us to using _python 2.6_ features. I think it can be safely written off, especially as our CI/CD only tests on Ubuntu 22.04 (though that should really be extended to include some other distros / releases)

Sorry, I think you have some wrong assumptions about the whole user base and the purpose of the CAT installer.

But let’s agree to disagree, and I am going to close the issue.
