### ISSUE TITLE
404 from Page Decoration

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#74]
# Issue type
- [ X] Defect - Crash/memory corruption.
## Detail of issue
overview_user not found in path

web/lib/admin/PageDecoration.php:33

<a href='/admin/overview_user.php'>" . _("Go to your Profile page") . "</a> 

(Added /admin)

**Comment by restena-sw** [comment]
this got implicitly fixed when removing the entire admin area page header. Since diagnostics is not an authenticated action in the future, the admin area header does not make sense any more. Even if we choose to reintroduce an admin-only policy, it would take a different form not depending on the admin area's PageDecoration class
