### ISSUE TITLE
Email failing to send fails to generate error

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#77]
# Issue type

- [ X] Defect - Unexpected behaviour (obvious or has been verified by a project member).

# Defect/Feature description
Check for failed send at the end of web/admin/inc/sendinvite.inc.php doesn't appear to work.

## How to reproduce issue
Configure receiving MTA to reject an email. 

Invite a new institution administrator.

CAT reports that the email has been sent, but it hasn't.
 
## Detail of issue
Check for failed send at the end of web/admin/inc/sendinvite.inc.php doesn't appear to work.
If additional logging is added then it can be seen that errors are produced but the code doesn't appear to 
be able to recognise them and deal with them.

**Comment by restena-sw** [comment]
This is mostly a matter of managing expectations. The function works just fine: it detects if getting the mail out to the world worked /technically/. I.e. we were able to contact the configured MTA and the MTA accepted the message for further delivery.
Maybe the mail address wasn't correct - in that case you get a bounce. But that happens out-of-band - the original SMTP connection is long closed.
We can be a bit more clever (but really only a bit): since we are now checking the existence of MX records before sending, we can throw a UI warning back if we find typos in the domain part which lead to an inexistent domain. But any more sophisticated errors, such as the local username part in the mail address being misselled, the target user being over quota, whatnot... are entirely outside our control.
I'm going to commit a change that catches the non-existent MX case and gives back an error. Please test that; it's less trivial than the other bug reports you opened.
And I'm afraid that's all we can do here.

**Comment by nevryn** [comment]
On Thu, Aug 10, 2017 at 11:17:54AM +0000, Stefan Winter wrote:
>    This is mostly a matter of managing expectations. The function works
>    just fine: it detects if getting the mail out to the world worked
>    /technically/. I.e. we were able to contact the configured MTA and the
>    MTA accepted the message for further delivery.
>    Maybe the mail address wasn't correct - in that case you get a bounce.
>    But that happens out-of-band - the original SMTP connection is long
>    closed.
>    We can be a bit more clever (but really only a bit): since we are now
>    checking the existence of MX records before sending, we can throw a UI
>    warning back if we find typos in the domain part which lead to an
>    inexistent domain. But any more sophisticated errors, such as the local
>    username part in the mail address being misselled, the target user
>    being over quota, whatnot... are entirely outside our control.
>    I'm going to commit a change that catches the non-existent MX case and
>    gives back an error. Please test that; it's less trivial than the other
>    bug reports you opened.
>    And I'm afraid that's all we can do here.

sendinvite is generating a connection failed message "SMTP connect() failed"
when attempting to talk to the MTA, and then still reporting a successful,
encrypted email sent but without the organisation appearing in the list
below.

I've seen it happen at various points in the dialog, including an inability
to find an 'AUTH' command.

If you want me to generate some examples then I can.

Separately, it seems to send a STARTTLS whether or not STARTTLS is advertised.
Not sure if this is the intended behaviour. 

Thanks,

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*
