### ISSUE TITLE
'Institution' replacement

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#80]
# Issue type
- [ X] New feature request.

# Feature description
The word 'institution' is associated more with academia than the commercial or public sector. Being able to replace this with a different word (such as 'organisation') would be useful.

**Comment by restena-sw** [comment]
I've been thinking about this choice of wording myself. It's a bit unlucky even in the eduroam context, as we have the two roles Identity Provider and Service Provider and "institution" doesn't make clear which role we are targeting.
I can change this to "Identity Provider" which would be compatible in all deployment contexts.
This is gonna take a while though:

"Found 1.239 matches of *institution* in 124 files."

And that's across class members, variable names, and actual display text in singular and plural forms.

**Comment by nevryn** [comment]
On Fri, Aug 11, 2017 at 12:23:50AM -0700, Stefan Winter wrote:
>    I've been thinking about this choice of wording myself. It's a bit
>    unlucky even in the eduroam context, as we have the two roles Identity
>    Provider and Service Provider and "institution" doesn't make clear
>    which role we are targeting.
>    I can change this to "Identity Provider" which would be compatible in
>    all deployment contexts.
>    This is gonna take a while though:
> 
>    "Found 1.239 matches of institution in 124 files."
> 
>    And that's across class members, variable names, and actual display
>    text in singular and plural forms.

I know :-( I've been through them all once to replace '[Ii]nstitution[s]
with '[Oo]rganisation[s]' in the text, just to see how practical it was. 
Only took an hour and a half.  But I wouldn't want to do that after every
update. 

I'm not sure about the idea of using 'Identity Provider'. For example:

"My Identity Provider is not listed. Can't I just use any of the other ones?
No! The installers contain security settings which are specific to the
Identity Provider. If you are not from that Identity Provider, your computer will detect
that you are about to send your username and credential to an unauthorised
server and will abort the login. Using a different Identity Provider installer is
guaranteed to not work!"

Identity Provider and Service Provider mean quite specific things which not
everyone is going to be able to grasp quickly enough to make them useful, even
administrators. 

Could this be treated like a translation? Academic-speak to corporate-speak?
Then we could put in our own choice of words. I'd be happy to do the
'translation' once.

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by restena-sw** [comment]
While coding, I also thought of making this configurable just to avoid iterative cycles of pain when changes are needed.
There is now a config item CONFIG['CONSORTIUM']['nomenclature_institution'] which can be set to a string of your choice.

Making this translatable is difficult because the translators can't know beforehand what you are going to enter in the config file later during deployment time. Given temporal continuity, this is a not solvable problem. What I can do is to pre-translate "common" values for that config item and translate them in the system. When the config item actually appears during runtime, it's taken, otherwise the original from the config file is used.

I'll add "Organisation" to the preloaded list - but could imagine eduroam to stick with Identity Provider.

You may run into capitalisation or a/an issues depending on your final choice of word. Fixing these grammar issues is not typically practicable; so if you want to be grammar-perfect some editing might still be needed afterwards. But let's see how far we get with this approach now.

This is not commited yet, might be until next week.

**Comment by restena-sw** [comment]
I'm also rearrangning wording to avoid plural grammar issues, and also use the same mechanism for "federation" where it occurs. Other consortia don't necessarily name their federations federations.

**Comment by restena-sw** [comment]
Done an commited. I may not have caught all variants of it - if you still see "institution", "IdP", "home institution", "home organisation" anywhere, please let me know.
