### ISSUE TITLE
Google maps window shows an error

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#83]
# Issue type
- [ X] Defect - Unexpected behaviour (obvious or has been verified by a project member).
# Defect/Feature description
The Google Maps aspect shows an error 'Ooops! Something went wrong' on loading the page.

## How to reproduce issue
Configure up an institution, go to the mangement page.
 
## Detail of issue
Javascript console shows:

js:35 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

Can be fixed by adding &key=XXXXXXXX to web/lib/admin/GeoWidgets.php line 40.

**Comment by restena-sw** [comment]
Thanks for noticing. Since the actual map display works, this never got its due consideration.
I was very happy when the Maps API v3 discontinued the requirement of a maps key - only to find out now that it got replaced with a new JS API key instead. 
I assume without key we were in some kind of grace mode, but that's of course not proper. I also noticed that "SensorNotRequired" is another warning we get, so I fixed both:
- removed sensor parameter
- added a config item APPEARANCE['google_maps_api_key]
You'll need to get your API key from
https://developers.google.com/maps/documentation/javascript/get-api-key?refresh=1
