### ISSUE TITLE
IdP-Logo-Cache is not correctly cleared

### ISSUE THREAD

**Issue by sklemer1** [GEANT/CAT#98]
When changing in IdP logo its cached files don't get deleted. I am not 100% sure if we some problem with our installation but from a quick view it seems that this is a real bug:

Cache invalidation upon logo change is done here:

https://github.com/GEANT/CAT/blob/17bffec48bbfa1c745292024ac0852607a9abb09/web/admin/edit_idp_result.php#L73

And as far as I can tell the only place where a cached file is used for the web is here
https://github.com/GEANT/CAT/blob/91a84b11084179711b05591811d67310d679e26e/web/user/API.php#L135

(ultimately leading to here:
https://github.com/GEANT/CAT/blob/91a84b11084179711b05591811d67310d679e26e/core/UserAPI.php#L352

)

So the filenames are different and the old logo is shown in the disco-dialogue. I'm not really sure how to fix it correctly while still be able to offer different sizes. I can only find files of this one size in my downloads/logo-folder:

$id_120_40.png

So perhaps one comes around without using some kind of wildcard-file-matching and deleting?

**Comment by restena-sw** [comment]
Inst logos have a bit of a journey behind them - we originally instantiated IdP objects and extracted the logos on the fly - this didn't need any caching, but turned out to be too slow when doing this for 50 logos at once for DiscoJuice.
It's well possible that there's an unsynced change between admin side cache logo deletion and usage of the cached logos.
@twoln can you look at this one? From a quick look I believe it's best to delete "/downloads/logos/" . $my_inst->identifier . "*" instead - or is it safe to restrict this to _120_40 instead?

**Comment by twoln** [comment]
Fixed the problem
